
import { Clinician } from './clinician';

export interface ClientDetails {
  id: string;
  client_first_name: string | null;
  client_last_name: string | null;
  client_email: string | null;
  client_phone: string | null;
  client_date_of_birth: string | null;
  client_preferred_name: string | null;
  client_assigned_therapist: string | null;
  client_diagnosis: string[] | null;
  client_planlength: string | null;
  client_treatmentfrequency: string | null;
  client_medications: string | null;
  client_personsinattendance: string | null;
  client_appearance: string | null;
  client_attitude: string | null;
  client_behavior: string | null;
  client_speech: string | null;
  client_affect: string | null;
  client_thoughtprocess: string | null;
  client_perception: string | null;
  client_orientation: string | null;
  client_memoryconcentration: string | null;
  client_insightjudgement: string | null;
  client_mood: string | null;
  client_substanceabuserisk: string | null;
  client_suicidalideation: string | null;
  client_homicidalideation: string | null;
  client_primaryobjective: string | null;
  client_secondaryobjective: string | null;
  client_tertiaryobjective: string | null;
  client_intervention1: string | null;
  client_intervention2: string | null;
  client_intervention3: string | null;
  client_intervention4: string | null;
  client_intervention5: string | null;
  client_intervention6: string | null;
  client_functioning: string | null;
  client_prognosis: string | null;
  client_progress: string | null;
  client_problem: string | null;
  client_treatmentgoal: string | null;
  client_sessionnarrative: string | null;
  client_nexttreatmentplanupdate: string | null;
  client_privatenote: string | null;
  client_status: string | null;
  client_time_zone: string | null;
  created_at?: string;
  updated_at?: string;
}
